language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
before_install:
  - npm install -g grunt-cli

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8



install:

  - npm install
